apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-16-16625
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap-test-organization-jk/rhtap-qe:93f40886f7e61f85c877085d96a65c3602cdbd24@sha256:e1230c7553ad0d564d3cda7fdce085469831403b7ee1952999ff7765a6608d6b
          name: container-image
