apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: go-16-16625
  janus-idp.io/tekton: go-16-16625
  backstage.io/kubernetes-id: go-16-16625
  backstage.io/kubernetes-namespace: tssc-new-app 
  app.kubernetes.io/part-of: go-16-16625
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
