apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: go-16-16625
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-16-16625 
  name: go-16-16625
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: go-16-16625 
